### ISSUE TITLE
TextRequest.Type has type mismatch between .NETclient library and API documentation

### ISSUE THREAD

**Issue by MartinJSoles** [Invoiced/api#21]
The API documentation indicates that the TextRequest type parameter expects either "open_item" or "balance_forward". The .NET client expects an int64. Should the client be updated to pass a string type or the documentation updated to reflect what the allowed integral values are?

**Comment by jaredtking** [comment]
That is definitely a mistake!

This appears to be the culprit: https://github.com/Invoiced/invoiced-dotnet/blob/master/invoicedapi/Entities/TextRequest.cs

**Comment by MartinJSoles** [comment]
I figured so after I went spelunking the other language packs and they all want text instead of numbers. :)

**Comment by MartinJSoles** [comment]
I added a pull request on the dotnet repository.
