### ISSUE TITLE
`Items` API endpoint doesn't work, but still present in the API documentations

### ISSUE THREAD

**Issue by ashr81** [Invoiced/api#22]
The APIs under this category don't exist, I request you to remove them from documentation or either fix the endpoints.

Link to endpoints [here](https://www.invoiced.com/resources/docs/api/#items)

**Comment by jaredtking** [comment]
Thank you for pointing this out. We're working on this and will have an update soon!

**Comment by jaredtking** [comment]
This should be working now. Thank you for reporting!
