### ISSUE TITLE
Invoice filter on balance amount is not working.

### ISSUE THREAD

**Issue by ashr81** [Invoiced/api#23]
I can query `/invoices` API with filter parameters like `filter[closed]:0`. But could not query with filter parameter:
`filter[balance]:0`. It throws an error: 
```
 {
  type: 'invalid_request',
  message: 'Invalid filter parameter: balance'
}
```
This works:
```
fetch(`https://api.invoiced.com/invoices?filter%5Bpaid%5D=0&filter%5Bclosed%5D=0`)
```
```
fetch(`https://api.invoiced.com/invoices?filter%5Bbalance%5D=0`)
```

**Comment by jaredtking** [comment]
Filtering by balance (or total) is not in the documentation although possible. Can you try this request and see if it works?

```
GET https://api.invoiced.com/invoices?balance=[">=",150]
```

With URL encoding:
```
GET https://api.invoiced.com/invoices?balance=%5B%22%3E%3D%22%2C150%5D
```

In this example you would receive invoices that have a balance >= 150

**Comment by ashr81** [comment]
@jaredtking That above suggestion worked. Do you have any plans to deprecate this query from the APIs as it's not documented?

**Comment by jaredtking** [comment]
No, this is not documented but is used in the web application. If you inspect the network calls while doing a balance filter in the web application you can see this parameter is used.

**Comment by ashr81** [comment]
@jaredtking  Thanks this is working. How do I report issues with Custom FIlters not appearing on Customer Portal after enabling Customer Visibility on the field?

**Comment by jaredtking** [comment]
You should contact our support team at support@invoiced.com to get help with issues specific to your account.
